# Preview all emails at http://localhost:3000/rails/mailers/invoice_mailer
class InvoiceMailerPreview < ActionMailer::Preview
    def new_order_email
        @pay = {
            "id": "in_1JSOUC2eZvKYlo2CQu1NY63Q",
            "object": "invoice",
            "account_country": "US",
            "account_name": "Stripe.com",
            "account_tax_ids": "null",
            "amount_due": 399,
            "amount_paid": 0,
            "amount_remaining": 399,
            "application_fee_amount": "null",
            "attempt_count": 0,
            "attempted": true,
            "auto_advance": true,
            "automatic_tax": {
              "enabled": false,
              "status": "null"
            },
            "billing_reason": "manual",
            "charge": "ch_3JSOUB2eZvKYlo2C18nabqdf",
            "collection_method": "charge_automatically",
            "created": 1629907076,
            "currency": "usd",
            "custom_fields": "null",
            "customer": "cus_91fz3aebyTniMk",
            "customer_address": "null",
            "customer_email": "kunal.kumbhar@scalereal.com",
            "customer_name": "null",
            "customer_phone": "null",
            "customer_shipping": "null",
            "customer_tax_exempt": "none",
            "customer_tax_ids": [],
            "default_payment_method": "null",
            "default_source": "null",
            "default_tax_rates": [],
            "description": "null",
            "discount": "null",
            "discounts": [],
            "due_date": "null",
            "ending_balance": "null",
            "footer": "null",
            "hosted_invoice_url": "null",
            "invoice_pdf": "null",
            "last_finalization_error": "null",
            "lines": {
              "object": "list",
              "data": [
                {
                  "id": "il_1JSOUC2eZvKYlo2C3xmCQBfi",
                  "object": "line_item",
                  "amount": 399,
                  "currency": "usd",
                  "description": "My First Invoice Item (created for API docs)",
                  "discount_amounts": [],
                  "discountable": true,
                  "discounts": [],
                  "invoice_item": "ii_1JSOUC2eZvKYlo2CpcJOl7tI",
                  "livemode": false,
                  "metadata": {},
                  "period": {
                    "end": 1629907076,
                    "start": 1629907076
                  },
                  "price": {
                    "id": "price_1JSLqt2eZvKYlo2Cp2mNFXXp",
                    "object": "price",
                    "active": true,
                    "billing_scheme": "per_unit",
                    "created": 1629896951,
                    "currency": "usd",
                    "livemode": false,
                    "lookup_key": "null",
                    "metadata": {},
                    "nickname": "null",
                    "product": "prod_K6YyY23CNd0I0o",
                    "recurring": "null",
                    "tax_behavior": "unspecified",
                    "tiers_mode": "null",
                    "transform_quantity": "null",
                    "type": "one_time",
                    "unit_amount": 399,
                    "unit_amount_decimal": "399"
                  },
                  "proration": false,
                  "quantity": 1,
                  "subscription": "null",
                  "tax_amounts": [],
                  "tax_rates": [],
                  "type": "invoiceitem"
                }
              ],
              "has_more": false,
              "url": "/v1/invoices/in_1JSOUC2eZvKYlo2CQu1NY63Q/lines"
            },
            "livemode": false,
            "metadata": {},
            "next_payment_attempt": 1629910676,
            "number": "80B2DEF-DRAFT",
            "on_behalf_of": "null",
            "paid": true,
            "payment_intent": "null",
            "payment_settings": {
              "payment_method_options": "null",
              "payment_method_types": "null"
            },
            "period_end": 1632072394,
            "period_start": 1629393994,
            "post_payment_credit_notes_amount": 0,
            "pre_payment_credit_notes_amount": 0,
            "quote": "null",
            "receipt_number": "null",
            "starting_balance": 0,
            "statement_descriptor": "null",
            "status": "paid",
            "status_transitions": {
              "finalized_at": "null",
              "marked_uncollectible_at": "null",
              "paid_at": "null",
              "voided_at": "null"
            },
            "subscription": "null",
            "subtotal": 399,
            "tax": "null",
            "total": 399,
            "total_discount_amounts": [],
            "total_tax_amounts": [],
            "transfer_data": "null",
            "webhooks_delivered_at": "null",
            "last_payment_attempt": "null"
          }
        InvoiceMailer.with(params: @pay).order_successful_email
    end

end
